---
- name: "Install Tmux"
  apt:
    name: tmux
    state: present
  become: true
  become_method: sudo

- name: "Create a directory tmux"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/tmux"
    state: directory
    mode: '0755'

- name: "Download tmux.conf"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/0xSixty6/setup-env/main/tmux.conf"
    dest: "{{ ansible_env.HOME }}/.config/tmux"
    mode: '0755'

