--- 
- name: "set os"
  hosts: localhost
  connection: local
  roles:
    - role: "main"
    - role: gantsign.visual-studio-code
      users:
        - username: "{{ ansible_user_id }}"
          visual_studio_code_extensions:
            - streetsidesoftware.code-spell-checker
            - ms-python.python
            - snyk-security.snyk-vulnerability-scanner
            - Blackboxapp.blackbox
